### ISSUE TITLE
TypeError: release.discs[discindex] is undefined

### ISSUE THREAD

**Issue by timeteam** [murdos/musicbrainz-userscripts#481] opened 2022-04-19 03:55 UTC
reporting error as requested:

https://www.discogs.com/release/20354791-Igor-Markevitch-Igor-Markevitch-The-Philips-Legacy

**Comment by kellnerd** [comment] 2024-01-17 00:17
Duplicate of #80

**Closed by kellnerd** 2024-01-17 00:17 UTC
