### ISSUE TITLE
[FMA import script] Album page that does not show import links

### ISSUE THREAD

**Issue by stragu** [murdos/musicbrainz-userscripts#122] opened 2016-09-17 09:41 UTC
Hi there

I just came across a particular page that does not work with the FMA import script:

http://freemusicarchive.org/music/SUBSET/SUBSET_meets_Netlabel_Day_2016_at_The_Dub_Factory/

It is the only problematic one I have found so far. The only odd thing I noticed with the page itself is that there is no "Album" header above the track list. See for example this other release by the same artist, which works like every other one:

http://freemusicarchive.org/music/SUBSET/Series70/

Any idea what the issue could be? @madmouser1 , you might have more of a clue than I do.

Cheers

**Comment by madmouser1** [comment] 2016-09-18 16:32
ah the musicbrainz import dialog is not showing (Album & Artist info is retreived correctly) 
I will have a look and amend.

**Comment by stragu** [comment] 2016-10-05 06:45
I just stumbled across another one: http://freemusicarchive.org/music/Project_5am/LAlchimiste/

Thanks for looking into it!

**Comment by madmouser1** [comment] 2018-02-08 09:10
Hi there @stragu ; I had a quick look and it is actually the FMA API returning "album_type":null and we expect the following classification to mark it as an album "album_type":"Album". The importer only handles Albums currently. So script work as intended issue is on FMA side.

**Comment by stragu** [comment] 2018-02-09 00:40
Right, that makes sense. I assume they don't want anything to not have an `album_type` value in their ideal database. Would it be helpful to have a simple message that tells the user why the importer can't handle that? Or leave the release's "primary type" blank when importing?
I just sent an email to the FMA to ask them about those `"album_type":null` releases.

The first linked release works fine now (the dialog shows), I assume you changed the script so it handles EPs too? (Although it still uses "album" as the release's "primary type" when importing.)

**Comment by madmouser1** [comment] 2018-12-27 11:01
FMA combining with other company, no further work will be done on this.
@murdos please close this.

**Closed** 2018-12-27 11:08 UTC
Labels: bug
